### ISSUE TITLE
CO2Signal API timeout

### ISSUE THREAD

**Issue by lfwa** [lfwa/carbontracker#1]
The CO2Signal API (co2signal.py) timeouts when multiple requests are sent consecutively. This renders the API almost useless (or at least when epochs_before_pred and monitor_epochs are the same).

**Comment by PedramBakh** [comment]
In [Release v1.2.0](https://github.com/lfwa/carbontracker/releases/tag/v1.2.0) we have phased out support for the standalone CO2Signal API in favor of its integration into the ElectricityMaps API. This transition ensures greater consistency and addresses previous timeout issues experienced with consecutive requests.
