### ISSUE TITLE
Support for monitoring outside training loops

### ISSUE THREAD

**Issue by lfwa** [lfwa/carbontracker#11]
Add support for monitoring energy and carbon footprint outside of training loops by tracker.start() and tracker.stop(). This can help track the consumption of setting up and preparing datasets and model inference.

**Comment by rongduo** [comment]
Hi @lfwa , thanks for releasing such a library, it's really cool.  
Have you added this feature? 
I need to measure the energy usage of the inference process of neural networks. 
Could you give me some tips to how to achieve this using your library?

**Comment by raghavian** [comment]
You can already do this by placing the tracker.start() and tracker.stop() between the points where the model is loaded for inference and predictions. Let us know if it works. 

For example:
```
tracker.start()
### Load trained model
### Perform inference
tracker.stop()
```

**Comment by rongduo** [comment]
Hi, thanks for your reply. When I tried to perform "tracer.start", I met a bug shown in the following figure.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/13198932/114201265-93d8e800-9988-11eb-83d7-cdef57b72b99.png">

Should I change "tracker.start()" to "tracker.begin()" ?

**Comment by raghavian** [comment]
Ah, the exact format is:
```
    tracker.epoch_start()
     # Your model training.
    tracker.epoch_end()
```
Check out the readme page.

**Comment by rongduo** [comment]
Thanks for your help, so sweet！
I ran it successfully.
