### ISSUE TITLE
Get actual time, energy, CO2eq programmatically

### ISSUE THREAD

**Issue by leondz** [lfwa/carbontracker#19]
Hi, how can one get the info in the printed report as an object instead? Going through printed output gets tough when there's a lot of it. If possible, a simple example on the README would be super handy

**Comment by lfwa** [comment]
Currently, your only option is to log your consumption to files (by providing the optional argument log_dir to the `CarbonTracker` class). These log files can then be parsed using the parser module, e.g. using `parser.parse_all_logs("./my_log_dir")`.

I updated the README to show an example of how this could be done after you have the log files. See [here](https://github.com/lfwa/carbontracker#convert-logs-to-dictionary-objects).
