### ISSUE TITLE
Naming log runs

### ISSUE THREAD

**Issue by leondz** [lfwa/carbontracker#26]
It'd be really helpful to be able to specify a prefix/infix/suffix label for individual logfiles, or otherwise attach metadata to them, so they can be easily connected to specific runs later. Great that the default is by date, to avoid collisions - this is a good feature. Can an optional parameter be added for adding a string to a log name?

**Comment by kanding** [comment]
Yeah, we can definitely look into adding this as an option in the future.

Our current thought-process was that you would use different naming on folders to group by model but I can see the usefulness of being able to distinguish between the specific runs as well!

**Comment by PedramBakh** [comment]
[Release 1.1.7](https://github.com/lfwa/carbontracker/releases/tag/1.1.7) adds the option of specifying a prefix for logfiles of individual instances of carbontracker. Moreover, logfiles now comprise their associated process ID to avoid collisions in cases where multiple short-duration measurements with several instances of carbontracker are present.
