### ISSUE TITLE
No carbonintensities when reporting actual usage

### ISSUE THREAD

**Issue by lfwa** [lfwa/carbontracker#30]
```
Traceback (most recent call last):
  File "/home/manvi/Documents/carbontracker/carbontracker/tracker.py", line 284, in epoch_end
    self._output_actual()
  File "/home/manvi/Documents/carbontracker/carbontracker/tracker.py", line 358, in _output_actual
    _co2eq = self._co2eq(energy)
  File "/home/manvi/Documents/carbontracker/carbontracker/tracker.py", line 381, in _co2eq
    ci = self.intensity_updater.average_carbon_intensity(pred_time_dur)
  File "/home/manvi/Documents/carbontracker/carbontracker/tracker.py", line 55, in average_carbon_intensity
    ci.carbon_intensity = self.carbon_intensities[-1].carbon_intensity
IndexError: list index out of range
```

_Originally posted by @agarwalmanvi in https://github.com/lfwa/carbontracker/issues/29#issuecomment-667152447_

**Comment by lfwa** [comment]
@agarwalmanvi I was able to reproduce this error by using **carbontracker** in a Python shell in interactive mode. However, I could not reproduce it in script mode. Were you using an interactive shell when you stumbled upon this error?

**Comment by agarwalmanvi** [comment]
Hi @lfwa , apologies for taking some time to respond. I came across this error while running the plain Python script described in [this comment](https://github.com/lfwa/carbontracker/issues/29#issuecomment-667146185). Were you able to figure out why the error showed up in interactive mode? Maybe that's the reason why it shows up with my script too.

**Comment by lfwa** [comment]
I looked to be an error from the changes introduced in commit 101f5fbcf9db1b8334bd3f8750e5b7ac7f393ebc. It seems to only occur for users for whom no live carbon intensity is available.

@agarwalmanvi 
Are you using **carbontracker** version 1.1.2 installed from pip or did you pull the package directly from GitHub?

**Comment by agarwalmanvi** [comment]
I pulled directly from GitHub and installed it using the `setup.py` file.

**Comment by agarwalmanvi** [comment]
> It looked to be an error from the changes introduced in commit [101f5fb](https://github.com/lfwa/carbontracker/commit/101f5fbcf9db1b8334bd3f8750e5b7ac7f393ebc). It seems to only occur for users for whom no live carbon intensity is available.

What's the recommended solution for this? Perhaps I can retry running my script with the solution to see if this error is solved!

**Comment by lfwa** [comment]
The error should be fixed if you pull the repo again. You can also pip install v1.1.2, where these late changes and errors does not exist.

Let me know if this solves it.
