### ISSUE TITLE
Make a CLI version that can accept arbitrary arguments

### ISSUE THREAD

**Issue by sagnik** [lfwa/carbontracker#32]
A CLI tool that can take a DL training command (and it's arguments) as arguments would be helpful. It doesn't need to show per epoch consumption: just the total one.

Here's an example use case:  `carbontracker <training-command> <*args>`.  The `training-command` can be something like `allennlp-train` or something else.

**Comment by PedramBakh** [comment]
Thank you for your suggestion. We're pleased to inform you that we have introduced a Command Line Interface (CLI) tool for CarbonTracker in our [latest release v1.2.0](https://github.com/lfwa/carbontracker/releases/tag/v1.2.0). This should essentially provide the functionality you were looking for.

Basic example:
`carbontracker --script train.py --log_dir ./logs`

Your usage example:
`carbontracker --script "train.py arg1 arg2 ..." --log_dir ./logs`

Given this new feature, I'm closing this issue. If you have any further feedback or face any issues with the new CLI tool, please don't hesitate to open a new issue.
