### ISSUE TITLE
Issue monitoring i7 CPU

### ISSUE THREAD

**Issue by raghavian** [lfwa/carbontracker#40]
Trying to use carbontracker on a new workstation on Ubuntu 20.04 (Intel i7-10700F CPU) and throws the following error:
```
with open(os.path.join(path, "energy_uj"), 'r') as f:
PermissionError: [Errno 13] Permission denied: '/sys/class/powercap/intel-rapl:0/energy_uj'
```
Most likely due to RAPL. Works when components="gpu" only.

**Comment by raghavian** [comment]
Looks like this is a Linux kernel update issue. To use carbontracker without this error, give read permission to the specific file:
```
sudo chmod 444 /sys/class/powercap/intel-rapl:0/energy_uj
```
If you do not have root access, ignore CPU monitoring when instantiating carbontracker:
```
tracker = CarbonTracker(epochs=args.num_epochs,components="gpu",
            log_dir='carbontracker/',monitor_epochs=-1)
```

**Comment by raghavian** [comment]
This will be an issue for users when they don't have root privileges. Will reopen the issue until we figure out a different solution.

**Comment by PedramBakh** [comment]
[Release 1.1.7](https://github.com/lfwa/carbontracker/releases/tag/1.1.7) adresses this issue by informing the user of missing privileges and refering to this issue thread.
