### ISSUE TITLE
"'str' object has no attribute 'decode' " while using pretrained model

### ISSUE THREAD

**Issue by Thire399** [lfwa/carbontracker#53]
I am getting this odd bug while trying to use the carbon tracker with a pretrained pytorch model and my own pytroch model.

![Screenshot from 2023-03-02 13-27-17](https://user-images.githubusercontent.com/43740426/222432276-37964f85-0dfa-47c7-a11d-389af22de49d.png)

For reference:
Ubuntu 20.04.5 LTS
GPU: GTX1070 8GB

**Comment by raghavian** [comment]
This is a duplicate of [Issue 52](https://github.com/lfwa/carbontracker/issues/52). I will close it here, please follow the solution presented there until we make a new release.

**Comment by dmdequin** [comment]
When getting the error  `AttributeError: 'str' object has no attribute 'decode'`, I was able to solve it by going to `carbontracker/components/gpu/nvidia.py"`  and commenting out line 25 where it says `devices = [name.decode("utf-8") for name in names]`, then adding `devices = names` on a line before the return statement of that function.

**Comment by PedramBakh** [comment]
This issue has been addressed in [Release v1.2.0](https://github.com/lfwa/carbontracker/releases/tag/v1.2.0). With Python 3.10's change in handling `char*` from C extensions, the string decoding for NVIDIA GPU names via NVML has been adjusted accordingly. This ensures compatibility across different Python versions.
