### ISSUE TITLE
Potential live carbon intensity API for France

### ISSUE THREAD

**Issue by lfwa** [lfwa/carbontracker#54]
In case we want to expand our regions with live carbon intensity measurements, I found a potential website that we can use as a source:
https://www.rte-france.com/eco2mix/les-emissions-de-co2-par-kwh-produit-en-france

**Comment by PedramBakh** [comment]
In [Release v1.2.0](https://github.com/lfwa/carbontracker/releases/tag/v1.2.0), we've integrated with the ElectricityMaps API, which includes data from `rte-france`, expanding our coverage to over 160 regions.
