### ISSUE TITLE
CLI: Can't pass command line arguments to script

### ISSUE THREAD

**Issue by lnicola** [lfwa/carbontracker#61]
The command line parsing should take a complete command line and pass the arguments to the user script at https://github.com/lfwa/carbontracker/blob/master/carbontracker/cli.py#L23.

**Comment by PedramBakh** [comment]
Thanks for bringing this to our attention. We've addressed your points in patch v1.2.1. You can now use the tool with arbitrary commands, like: `carbontracker myscript arg1 arg2 --log_dir ./logs`.
