### ISSUE TITLE
Print statements going in overdrive

### ISSUE THREAD

**Issue by andreasgoethals** [lfwa/carbontracker#70]
When I run the CarbonTracker code, it always gives way too many print statements. Everytime you instantiate a tracker object it adds another line to the print statement, coming to this: CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: The following components were found: GPU with device(s) Tesla V100-SXM2-16GB.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Epoch duration is too short for a measurement to be collected.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: WARNING - Failed to retrieve carbon intensity: Defaulting to average carbon intensity 357.2021 gCO2/kWh.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: Average carbon intensity during training was 357.20 gCO2/kWh at detected location: Council Bluffs, Iowa, US.
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: 
Actual consumption:
	Time:	0:00:00
	Energy:	0.000000000000 kWh
	CO2eq:	0.000000000000 g
	This is equivalent to:
	0.000000000000 km travelled by car
CarbonTracker: Finished monitoring.
CarbonTracker: Finished monitoring.
CarbonTracker: Finished monitoring.
CarbonTracker: Finished monitoring.
CarbonTracker: Finished monitoring.
CarbonTracker: Finished monitoring.
CarbonTracker: Finished monitoring.
CarbonTracker: Finished monitoring.
CarbonTracker: Finished monitoring.
CarbonTracker: Finished monitoring.

**Comment by Snailed** [comment]
Hello, thank you for reporting this issue. I experience it as well.
I will take a look and try to fix this.

**Comment by Snailed** [comment]
Resolved in Carbontracker v2.0.0.
